export const ALL_ITEM_REQUEST = "ALL_ITEM_REQUEST";
export const ALL_ITEM_SUCCESS = "ALL_ITEM_SUCCESS";
export const ALL_ITEM_FAIL = "ALL_ITEM_FAIL";

export const ITEM_DETAILS_REQUEST = "ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = "ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_FAIL = "ITEM_DETAILS_FAIL";

export const NEW_ITEM_REQUEST = "NEW_ITEM_REQUEST";
export const NEW_ITEM_SUCCESS = "NEW_ITEM_SUCCESS";
export const NEW_ITEM_RESET = "NEW_ITEM_RESET";
export const NEW_ITEM_FAIL = "NEW_ITEM_FAIL";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_RESET = "UPDATE_ITEM_RESET";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_RESET = "DELETE_ITEM_RESET";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";